HEAT = [
["Classification & primes",8,"L1","How many primes up to 100, which is irrational, recurring decimal → fraction, primes adding to a total"],
["Unit digit",14,"L2","Unit digit of a product/sum of big powers, factorial sums"],
["Number of factors",12,"L3","Total, even, odd, perfect-square and ‘divisible by k’ factors"],
["Sum & product of factors",5,"L4","Sum of even/odd factors, product N^(n/2)"],
["Divisibility & missing digit",16,"L5","Find x, y so that a number is divisible by 72, 88, 7-11-13"],
["Counting multiples",6,"L6","Divisible by both / either / neither in a range"],
["Remainder rules",14,"L7","Remainder of sums and products, least number to add, successive division"],
["Remainder of powers",9,"L8","(D ± 1)ⁿ, aⁿ ± bⁿ, Fermat, Wilson"],
["Trailing zeros",6,"L9","Zeros at the end of n!, highest power of a prime"],
["Digits & pages",3,"L10","Digits to number a book, how often a digit appears"],
["Reversed digits & x² − y²",5,"L11","Two-digit number and its reverse, pairs with a given difference of squares"],
["Number bases",2,"L12","Binary ↔ decimal ↔ octal ↔ hex"],
["Series sums",8,"L13","Σn, Σn², Σn³, odd/even sums, AP sums"]
]
TILES = [
["25","primes from 1 to 100 (46 to 200, 168 to 1000)"],["2","only even prime; 1 is neither prime nor composite"],
["101 · 997","smallest and largest 3-digit primes"],["6k ± 1","form of every prime above 3"],
["ab/99","0.ababab… ;  (ab − a)/90 for 0.abbb…"],["2, 4, 8, 6","cycle of 2 (3: 3, 9, 7, 1; 7: 7, 9, 3, 1; 8: 8, 4, 2, 6)"],
["r = 0 → 4","power ÷ 4 leaves 0: use the 4th term"],["3","unit digit of 1! + 2! + … + n! (n ≥ 4)"],
["(p+1)(q+1)(r+1)","number of factors of aᵖbᵠcʳ"],["N^(n/2)","product of all factors"],
["σ(N)/N","sum of reciprocals of factors"],["6, 28, 496","perfect numbers"],
["1001","7 × 11 × 13 → abcabc"],["10101","3 × 7 × 13 × 37 → ababab"],
["+4 × last","test for 13 (17: −5 × last)"],["D − R","least number to add (R to subtract)"],
["k·LCM + r","same remainder r for every divisor"],["(D − 1)ⁿ","→ 1 if n even, D − 1 if n odd"],
["a^(p−1) → 1","Fermat (p prime)"],["(p − 1)! → p − 1","Wilson"],["φ(100) = 40","Euler’s totient"],
["24 · 249","zeros at the end of 100! and 1000!"],["9, 189, 2889","digits to write 1–9, 1–99, 1–999"],
["901","sum of digits from 1 to 100"],["11(x+y) · 9(x−y)","two-digit number ± its reverse"],
["4k + 2","never a difference of two squares"],["8-4-2-1","binary ↔ hex in groups of 4 (4-2-1 for octal)"],
["[n(n+1)/2]²","1³ + 2³ + … + n³"]
]
PAIRS = [
["Prime vs co-prime","prime: exactly 2 factors; co-prime: two numbers with HCF 1 (8 and 9)"],
["Power ÷ 4 leaves 0","use the 4th term (2⁴ → 6), not 2⁰ = 1"],
["Odd factors vs even factors","odd: drop the 2s; even: total − odd"],
["Composite factors","total − prime factors − 1 (1 is neither)"],
["Divisible by 4 and 6 vs by 24","24 needs co-prime parts 3 and 8; 12 is divisible by 4 and 6"],
["Least to add vs least to subtract","D − R vs R"],
["(D − 1)ⁿ: n even vs n odd","1 vs D − 1"],
["aⁿ + bⁿ vs aⁿ − bⁿ","+ divisible by a + b for odd n; − divisible by a − b always and by a + b for even n"],
["Fermat vs Euler","Fermat needs a prime divisor; Euler works for any co-prime N with φ(N)"],
["Zeros in n! vs in a product","n!: count 5s; plain product: min(2s, 5s)"],
["⌊n/5⌋ only vs + ⌊n/25⌋ + …","25 gives two 5s, 125 three — keep dividing"],
["Numbers with a 7 vs number of 7s","19 numbers but 20 sevens from 1 to 100 (77)"],
["x² − y² = 36: 6 × 6","gives y = 0 → not a pair of natural numbers"],
["(2⁶¹ + 3⁶¹ + 4⁶¹) ÷ 9","remainder 6, not 0 — AP terms only pair up as first + last"],
["Binary grouping","from the right in 3s (octal) or 4s (hex)"]
]
COVERS = {
 "cyc":{"tab":"Unit-digit drill","hideLabel":"Hide answers","note":"Cover the answer and find each unit digit in your head with the cycle rule.","head":["Expression","Rule","Unit digit"],"hide":2,"rows":[
  ["2^575","75 ÷ 4 → 3","8"],["3^236","36 ÷ 4 → 0 → 4th","1"],["7^282","82 ÷ 4 → 2","9"],["8^253","53 ÷ 4 → 1","8"],["4^1997","odd power","4"],["9^1000","even power","1"],
  ["2^644","44 ÷ 4 → 0 → 4th","6"],["7^95","95 ÷ 4 → 3","3"],["13^2003","03 ÷ 4 → 3","7"],["1!+…+100!","only 1!–4!","3"],["2383 − 1689","13 − 9","4"],["odd × 5","always","5"]]},
 "fac":{"tab":"Factor drill","hideLabel":"Hide answers","note":"Cover the answer: factorise, then apply the counting formula.","head":["Question","Factorisation","Answer"],"hide":2,"rows":[
  ["Factors of 360","2³ × 3² × 5","24"],["Odd factors of 360","3² × 5","6"],["Even factors of 360","24 − 6","18"],["Factors of 720","2⁴ × 3² × 5","30"],
  ["Composite factors of 720","30 − 3 − 1","26"],["Square factors of 720","3 × 2 × 1","6"],["Cube factors of 720","2 × 1 × 1","2"],["Factors of 720 divisible by 10","72 = 2³ × 3²","12"],
  ["Sum of factors of 360","15 × 13 × 6","1170"],["Sum of odd factors of 720","13 × 6","78"],["Sum of even factors of 720","30 × 13 × 6","2340"],["Product of factors of 360","24 factors","360¹²"],
  ["Co-prime pairs of 56","4 × 2 + 3","11"],["Co-prime pairs of 720","30 + 14 + 24","68"]]},
 "rem":{"tab":"Remainder drill","hideLabel":"Hide answers","note":"Cover the answer and name the rule that gives it.","head":["Expression","Rule","Remainder"],"hide":2,"rows":[
  ["16¹³ ÷ 15","(D + 1)ⁿ","1"],["72²⁸² ÷ 73","(D − 1)^even","1"],["72²⁸¹ ÷ 73","(D − 1)^odd","72"],["(8³⁷¹ + 5³⁷¹) ÷ 13","odd n, a + b = 13","0"],
  ["(7²⁴ − 4²⁴) ÷ 11","even n, a + b = 11","0"],["(8³⁶ − 2³⁶) ÷ 6","a − b = 6","0"],["82⁵⁴ ÷ 19","Fermat (18)","1"],["93⁵¹ ÷ 11","5⁵¹, Fermat (10)","5"],
  ["40! ÷ 41","Wilson","40"],["2¹⁰⁰ ÷ 7","2³ → 1","2"],["89 ÷ 9","90 − 1","8"],["(4x − 2y + 3z) ÷ 31, rem 17, 24, 27","68 − 48 + 81 = 101","8"]]}
}
FIND = {"tab":"Formula finder","ph":"Search a formula (e.g. factors, 13, zeros, hex)","head":["Topic","Formula","Lesson","When to use"],"rows":[
["Number types","natural ⊂ whole ⊂ integer ⊂ rational ⊂ real","L1","Classify a number"],
["Prime count","25 to 100, 46 to 200, 95 to 500, 168 to 1000","L1","How many primes"],
["Prime test","test primes up to √N","L1","Is N prime?"],
["Prime form","every prime > 3 is 6k ± 1","L1","Quick filter"],
["Recurring decimal","0.abab… = ab/99; 0.abbb… = (ab − a)/90","L1","Decimal → fraction"],
["Terminating decimal","denominator has only 2s and 5s","L1","Does P/Q end?"],
["Unit digit cycles","2: 2486, 3: 3971, 7: 7931, 8: 8426; 4, 9 alternate","L2","Unit digit of a power"],
["Unit digit method","power (last 2 digits) ÷ 4; remainder 0 → 4","L2","Big powers"],
["Factorial unit digit","n! ends in 0 for n ≥ 5; 1! + … + n! ends in 3","L2","Factorial sums"],
["Last two digits","base …1: tens = unit digit of (tens × power)","L2","Last two digits"],
["Number of factors","(p + 1)(q + 1)(r + 1)","L3","Count factors"],
["Odd / even factors","odd: drop 2s; even = total − odd","L3","Even/odd factors"],
["Composite factors","total − primes − 1","L3","Composite count"],
["Square / cube factors","⌊p/2⌋ + 1 / ⌊p/3⌋ + 1 per prime","L3","Special factors"],
["Factors divisible by k","factors of N/k","L3","Divisible factors"],
["Co-prime factor pairs","(p + 1)(q + 1) + pq","L3","Pairs with HCF 1"],
["Ways as product of two","n/2 or (n + 1)/2 for squares","L3","N = A × B"],
["Sum of factors","Π (a^(p+1) − 1)/(a − 1)","L4","Sum of all factors"],
["Sum of odd / even factors","drop the 2-bracket / all − odd","L4","Odd/even sums"],
["Product of factors","N^(n/2)","L4","Product"],
["Sum of reciprocals","σ(N)/N","L4","Reciprocal sum"],
["Divisible by 2ⁿ","last n digits divisible by 2ⁿ","L5","2, 4, 8, 16"],
["Divisible by 3, 9","digit sum","L5","Missing digit"],
["Divisible by 11","alternate digit sum difference 0 or 11k","L5","Missing digit"],
["Divisible by 7","triplets alternately, or double last and subtract","L5","7 test"],
["Divisible by 13","add 4 × last digit","L5","13 test"],
["Divisible by 17","subtract 5 × last digit","L5","17 test"],
["7, 11, 13","abcabc = abc × 1001","L5","Repeated triplets"],
["3, 7, 13, 37","ababab = ab × 10101","L5","Repeated pairs"],
["Composite divisor","split into co-prime parts (72 = 8 × 9)","L5","Divisible by 72, 88 …"],
["Multiples in A..B","⌊B/k⌋ − ⌊(A − 1)/k⌋","L6","Count multiples"],
["Either / neither","N(a) + N(b) − N(LCM); total − that","L6","Inclusion–exclusion"],
["Division","N = DQ + R","L7","Find the number"],
["Remainder of sum/product","combine remainders","L7","Big sums and products"],
["Negative remainder","r − D, add D back at the end","L7","Near multiples"],
["Least to add / subtract","D − R / R","L7","Make divisible"],
["Same remainder","k × LCM + r","L7","Leaves r each time"],
["Constant gap","k × LCM − d","L7","Remainders 1 less than divisors"],
["Successive division","rebuild from the last: × divisor + remainder","L7","Find N"],
["(D ± 1)ⁿ","+1 → 1; −1 → 1 (even n) or D − 1 (odd n)","L8","Big powers"],
["aⁿ ± bⁿ","+: ÷ (a + b) for odd n; −: ÷ (a − b) always, ÷ (a + b) for even n","L8","Sum/difference of powers"],
["Fermat","a^(p−1) → 1 (mod p)","L8","Prime divisor"],
["Euler","a^φ(N) → 1; φ(N) = N Π(1 − 1/p)","L8","Any divisor"],
["Wilson","(p − 1)! → p − 1; (p − 2)! → 1","L8","Factorial ÷ prime"],
["Trailing zeros of n!","⌊n/5⌋ + ⌊n/25⌋ + …","L9","Zeros"],
["Power of p in n!","Σ ⌊n/pᵏ⌋","L9","Highest power"],
["Composite base in n!","limiting prime (12 = 2² × 3)","L9","Power of 12, 6 …"],
["Digits for 1..N","n(N + 1) − 11…1","L10","Page numbering"],
["Digit frequency","each 1–9: 20 times in 1–99, 300 in 1–999","L10","How often a digit appears"],
["Sum of digits","1–100: 901; 1–999: 13500","L10","Digit sums"],
["Difference of squares","N = (x + y)(x − y), same parity","L11","Pairs (x, y)"],
["Reversed 2-digit","sum 11(x + y), difference 9(x − y)","L11","Digits interchanged"],
["Reversed 3-digit","99(x − z), 90(x − y), 9(y − z)","L11","Digits interchanged"],
["To decimal","Σ digit × baseᵖˡᵃᶜᵉ","L12","Any base → 10"],
["From decimal","divide repeatedly, remainders bottom-up","L12","10 → any base"],
["Binary ↔ octal / hex","groups of 3 (4-2-1) / 4 (8-4-2-1)","L12","Quick conversion"],
["Σn, Σn², Σn³","n(n+1)/2, n(n+1)(2n+1)/6, [n(n+1)/2]²","L13","Series sums"],
["Odd / even sums","n² / n(n + 1)","L13","1 + 3 + … , 2 + 4 + …"],
["AP","n = (l − a)/d + 1, S = n(a + l)/2","L13","Terms and sum"]
]}
APP = {"key":"number_system_workbook_v1","brand":"Number System","sub":"संख्या पद्धति · SSC maths workbook","eyebrow":"SSC CGL Maths",
 "intro":"Thirteen lessons that cover every number-system type SSC asks: classification and primes, unit digits, number, sum and product of factors, divisibility and missing digits, counting multiples, remainders and the remainder theorems, trailing zeros, digit counting, reversed digits and difference of squares, number bases and series sums. Built from the Formula Book chapter with extra topics SSC also asks. Each lesson has formula cards, solved examples, tricks and traps, and a practice bank whose answers are checked by computer.",
 "foot":"Read a lesson’s formula cards and examples, then try its quick check and question bank. Use the drills to cover a column and recall it, and the formula finder to look anything up in seconds. Revisit the traps before a mock test.",
 "craft":"Most number-system questions fall to four moves. (1) Factorise first: factors, sums, zeros and HCF/LCM all start from N = aᵖbᵠcʳ. (2) Work with remainders, not numbers: replace every term by its remainder (or unit digit), allow negative remainders, and look for divisor ± 1. (3) Split a composite divisor into co-prime parts (72 = 8 × 9) for missing digits. (4) Use options: the answer to a reversed-digit question is a multiple of 9 or 11, a perfect square has an odd number of factors, and a remainder is always smaller than the divisor.",
 "heatNote":"Shares are approximate, estimated from recent SSC CGL and CHSL papers; they show where number-system questions usually come from, not exact counts."}
